### ISSUE TITLE
Is there any upcoming support for AMD graphic cards?

### ISSUE THREAD

**Issue by kvnptl** [turlucode/ros-docker-gui#10]
My laptop specs: 
**Processor**: AMD® Ryzen 5 4600h with radeon graphics × 12 
**Graphics**: AMD® Radeon rx 5600m / AMD® Renoir

**Comment by atasoglou** [comment]
We definitely want to add support for AMD graphic cards, but we don't have one at our disposal at the moment to add support.

**Comment by turlucode** [comment]
supported with v3 now
