### ISSUE TITLE
CUDA Version: N/A??

### ISSUE THREAD

**Issue by hitch22** [turlucode/ros-docker-gui#12]
Hi,

I compiled turlucode/ros-noetic:cuda11.4.2-cudnn8 

and ran it with the below docker cmd:

docker run --rm -it --runtime=nvidia --privileged --net=host --ipc=host \
-v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY \
-v $HOME/.Xauthority:/home/$(id -un)/.Xauthority -e XAUTHORITY=/home/$(id -un)/.Xauthority \
-e DOCKER_USER_NAME=$(id -un) \
-e DOCKER_USER_ID=$(id -u) \
-e DOCKER_USER_GROUP_NAME=$(id -gn) \
-e DOCKER_USER_GROUP_ID=$(id -g) \
-e ROS_IP=127.0.0.1 \
turlucode/ros-noetic:cuda11.4.2-cudnn8

yet, inside the container, CUDA doesn't seem to be loaded inside the container:
❯ nvidia-smi 
Fri Mar  4 04:18:18 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P620         Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P3    N/A /  N/A |    523MiB /  4042MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

any suggestions?

Thanks in advance!

**Comment by atasoglou** [comment]
Hello @hitch22. You still have the issue? I just compiled the image and it seems it is working fine for me. I found [this](https://github.com/NVIDIA/nvidia-docker/issues/1460) that could be relevant for your case.
