### ISSUE TITLE
Make cpu_ros_melodic fails no pip<21

### ISSUE THREAD

**Issue by richtong** [turlucode/ros-docker-gui#14]
OK, I'm trying to build the cpu version of melodic, but this dockerfile is failing in the paramiko installation, it is looking for pip<21 to install virtualenv

But the build says there is no pip version under 21 

The dockerfile in ./cpu/melodic/base/Dockerfile

```
RUN /usr/bin/yes | pip install --upgrade "pip < 21.0"
RUN /usr/bin/yes | pip install --upgrade virtualenv
RUN /usr/bin/yes | pip install --upgrade paramiko
```

And I'm pretty sure that there is a version pinning problem here. Sigh Python 2.7 support sucks!

**Comment by richtong** [comment]
OK, I'm not sure why pip was pinned that low with v22 running, but I removed this and Paramiko needs some apt-get packages installed.

You might want to consider installing some github actions which will run all the dockerfiles and also pushing them into dockerhub (as this is free for open source), so people can just pull them rather than building their own. I can help with that if you like

**Comment by atasoglou** [comment]
Probably this is why we decided to use `pip install --upgrade "pip < 21.0"`: https://stackoverflow.com/questions/65558034/cant-install-pip-anymore-with-python-2-7

**Comment by atasoglou** [comment]
> OK, I'm trying to build the cpu version of melodic, but this dockerfile is failing in the paramiko installation, it is looking for pip<21 to install virtualenv
> 
> But the build says there is no pip version under 21
> 
> The dockerfile in ./cpu/melodic/base/Dockerfile
> 
> ```
> RUN /usr/bin/yes | pip install --upgrade "pip < 21.0"
> RUN /usr/bin/yes | pip install --upgrade virtualenv
> RUN /usr/bin/yes | pip install --upgrade paramiko
> ```
> 
> And I'm pretty sure that there is a version pinning problem here. Sigh Python 2.7 support sucks!

I quickly checked the changes you propose, although this builds, inside the container you get
```
pip --version
/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

So I am gonna keep the original file since I cannot reproduce it.
