### ISSUE TITLE
RROR: failed to solve: process "/bin/sh -c apt-key adv --keyserver

### ISSUE THREAD

**Issue by MohamedNagyMostafa** [turlucode/ros-docker-gui#18]
Hello, 

I tried to build 'make nvidia_ros_melodic_cuda11-4-2_cudnn8'; however, the process is interrupted by this error.

![Screenshot from 2023-06-20 10-58-13](https://github.com/turlucode/ros-docker-gui/assets/20774864/89740017-cfd1-47cc-8ccb-3122614a7811)

**Comment by atasoglou** [comment]
closing as issue reported cannot be reproduced
