### ISSUE TITLE
Error when running Gui applications 

### ISSUE THREAD

**Issue by Jovian-Dsouza** [turlucode/ros-docker-gui#6]
I installed nvidia-ros-kinetic , but I get this message when I run docker container also I am not able to load the Gui apps.

```
Gtk-Message: Failed to load module "canberra-gtk-module"
PluginRegistry::load_plugins: Importing plugin __init__.py failed: 'module' object has no attribute 'AVAILABLE'
```

**Comment by atasoglou** [comment]
Hello Jovian, I am building it right now to see if I am also getting it.

In the meantime a few questions that might shed some light:
I guess you checked that `nvidia-docker` is running fine as explained here: https://github.com/turlucode/ros-docker-gui#install-nvidia-docker-plugin ? E.g. is `nvidia-smi` producing the correct output within docker?

What do you get if you run in your **host**:
```
glxinfo|egrep "OpenGL vendor|OpenGL renderer"
```

**Comment by atasoglou** [comment]
Just finished building `make nvidia_ros_kinetic`. It works fine for me. If I run `glxgears` the window with the moving gears pops-up.

**Comment by Jovian-Dsouza** [comment]
Thanks @atasoglou  , `glxgears` is working . I got it to work after running  this in the docker instance
```sudo apt install libcanberra-gtk0 libcanberra-gtk-module```
